# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run testsuite
        run: |
          git clone https://github.com/michielbdejong/ocm-stub
          /bin/bash ./gencerts.sh
          /bin/bash ./rebuild.sh

          /bin/bash ./scripts/run-test.sh "Share-with flow" "Stub" "Stub"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Stub" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Stub" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Stub" "Reva"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Stub" "Revanc"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "ownCloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "ownCloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "ownCloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "ownCloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "ownCloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Nextcloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Nextcloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Nextcloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Nextcloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Nextcloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Reva" "Stub"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Reva" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Reva" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Reva" "Reva"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Reva" "Revanc"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Revanc" "Stub"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Revanc" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Revanc" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Revanc" "Reva"
          /bin/bash ./scripts/run-test.sh "Share-with flow" "Revanc" "Revanc"

          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Stub" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Stub" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Stub" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Stub" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Stub" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "ownCloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "ownCloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "ownCloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "ownCloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "ownCloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Nextcloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Nextcloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Nextcloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Nextcloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Nextcloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Reva" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Reva" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Reva" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Reva" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Reva" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Revanc" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Revanc" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Revanc" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Revanc" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in first" "Revanc" "Revanc"

          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Stub" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Stub" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Stub" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Stub" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Stub" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "ownCloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "ownCloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "ownCloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "ownCloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "ownCloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Nextcloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Nextcloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Nextcloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Nextcloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Nextcloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Reva" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Reva" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Reva" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Reva" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Reva" "Revanc"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Revanc" "Stub"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Revanc" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Revanc" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Revanc" "Reva"
          /bin/bash ./scripts/run-test.sh "Public link flow, log in after" "Revanc" "Revanc"

          /bin/bash ./scripts/run-test.sh "Invite flow" "Stub" "Stub"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Stub" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Stub" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Stub" "Reva"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Stub" "Revanc"
          /bin/bash ./scripts/run-test.sh "Invite flow" "ownCloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Invite flow" "ownCloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "ownCloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "ownCloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Invite flow" "ownCloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Nextcloud" "Stub"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Nextcloud" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Nextcloud" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Nextcloud" "Reva"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Nextcloud" "Revanc"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Reva" "Stub"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Reva" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Reva" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Reva" "Reva"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Reva" "Revanc"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Revanc" "Stub"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Revanc" "ownCloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Revanc" "Nextcloud"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Revanc" "Reva"
          /bin/bash ./scripts/run-test.sh "Invite flow" "Revanc" "Revanc"
